[package]
name = "hwp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
cfb = "0.7"
flate2 = "1.0"
num = "0.4"
openssl = "0.10"
